all:
  vars:
    ansible_ssh_private_key_file: test.pem
    ansible_user: ec2-user
  hosts:  # all ungrouped hosts

  children: # group of hosts
    webservers: # First group of hosts
      vars:
     #   ansible_ssh_private_key_file: test.pem
    #    ansible_user: ec2-user
      hosts:
        web1:
          ansible_host: 172.31.31.81
        web2: 
          ansible_host: 172.31.26.22
    
    database: # Second group of hosts
      hosts:
        dbserver:
          ansible_host: 172.31.26.222
          ansible_user: ec2-user