---
- name: Adding users
  hosts: database
  become: yes
#  vars:
#    user: local1
#    comm: adding from local1 vars
  tasks:
    - name: Create user 
      user:
        name: "{{name}}"
        state: present
        comment: "{{comm}}"
      register: userout
    
    - name: print output of user name
      debug:
        var: userout.name
    - name: print output of user name
      debug:
        var: userout.comment