all:
  hosts: # ungrouped hosts

  children:
    webservers:
      hosts:
        web1:
          ansible_host: 172.31.31.81
        web2:
          ansible_host: 172.31.26.22

    database: # Second group of hosts
      hosts:
        dbserver1:
          ansible_host: 172.31.40.4
        dbserver2:
          ansible_host: 172.31.33.255
          ansible_user: ubuntu

  vars:
    ansible_ssh_private_key_file: test.pem
    ansible_user: ec2-user      
    